"""
crypto/signature_engine.py

Ed25519 Signature Engine for VFEL.

Ed25519 is the standard choice for high-performance signature systems:
- 64-byte signatures (compact)
- ~100k sign/verify operations per second per core
- Deterministic: same key + message → same signature (no random nonce needed)
- Resistant to side-channel attacks by design
- Used by: SSH, TLS 1.3, Signal, Ethereum 2.0, Solana

Dependency: Python's `cryptography` library (standard in most environments)
    pip install cryptography

Key format:
    Private key: 32 bytes (stored as PEM or raw bytes)
    Public key: 32 bytes (DER or raw bytes)
    Signature: 64 bytes

VFEL signs:
    - Block headers (Phase 4) — proves authorship of a block
    - Anchor records (Phase 7) — proves anchoring authority
    - Proof responses (Phase 6) — proves proof was generated by authorized node

What VFEL does NOT sign per-event (by design):
    Events are integrity-protected by their Merkle inclusion in a signed block,
    not individually signed. Per-event signatures at 1M+ eps would be prohibitive.
    The VCP original_signature field is preserved but not re-verified here —
    that's Phase 6 (ordering_proof / inclusion_proof).
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from typing import Optional, Union

logger = logging.getLogger(__name__)

try:
    from cryptography.hazmat.primitives.asymmetric.ed25519 import (
        Ed25519PrivateKey,
        Ed25519PublicKey,
    )
    from cryptography.hazmat.primitives.serialization import (
        Encoding, PublicFormat, PrivateFormat, NoEncryption,
        load_pem_private_key, load_der_public_key,
    )
    from cryptography.exceptions import InvalidSignature
    CRYPTO_AVAILABLE = True
except ImportError:
    CRYPTO_AVAILABLE = False
    logger.warning(
        "cryptography library not installed — signatures disabled. "
        "Install with: pip install cryptography"
    )


# ──────────────────────────────────────────────
# Key pair model
# ──────────────────────────────────────────────

@dataclass
class KeyPair:
    """
    An Ed25519 key pair with its VFEL key_id.
    key_id is a short identifier used to reference keys in the key registry.
    """
    key_id: str
    private_key_pem: bytes     # PEM-encoded private key
    public_key_raw: bytes      # Raw 32-byte public key (for compact storage)
    public_key_hex: str        # Hex string of public key (for JSON embedding)

    @classmethod
    def generate(cls, key_id: str) -> "KeyPair":
        """Generate a new Ed25519 key pair."""
        if not CRYPTO_AVAILABLE:
            raise RuntimeError("cryptography library required for key generation")

        private_key = Ed25519PrivateKey.generate()
        public_key = private_key.public_key()

        private_pem = private_key.private_bytes(
            Encoding.PEM, PrivateFormat.PKCS8, NoEncryption()
        )
        public_raw = public_key.public_bytes(Encoding.Raw, PublicFormat.Raw)

        return cls(
            key_id=key_id,
            private_key_pem=private_pem,
            public_key_raw=public_raw,
            public_key_hex=public_raw.hex(),
        )

    def to_dict(self) -> dict:
        """Serialize (private key excluded — never serialize private keys to untrusted storage)."""
        return {
            "key_id":         self.key_id,
            "public_key_hex": self.public_key_hex,
            "algorithm":      "Ed25519",
        }


# ──────────────────────────────────────────────
# Signature result
# ──────────────────────────────────────────────

@dataclass(frozen=True)
class SignatureResult:
    signature_hex: str
    key_id: str
    algorithm: str = "Ed25519"

    def to_dict(self) -> dict:
        return {
            "signature": self.signature_hex,
            "key_id":    self.key_id,
            "algorithm": self.algorithm,
        }


# ──────────────────────────────────────────────
# Signature Engine
# ──────────────────────────────────────────────

class SignatureEngine:
    """
    Ed25519 sign and verify operations.

    Requires the `cryptography` library.
    If unavailable, all operations raise RuntimeError with install instructions.

    Usage:
        engine = SignatureEngine()
        kp = KeyPair.generate("node-1")
        sig = engine.sign(b"data to sign", kp)
        ok = engine.verify(b"data to sign", sig.signature_hex, kp.public_key_hex)
    """

    def sign(self, message: Union[bytes, str], key_pair: KeyPair) -> SignatureResult:
        """
        Sign a message with the given key pair.
        message: raw bytes or string (UTF-8 encoded)
        Returns SignatureResult with hex-encoded signature.
        """
        self._require_crypto()
        if isinstance(message, str):
            message = message.encode("utf-8")

        private_key = load_pem_private_key(key_pair.private_key_pem, password=None)
        signature_bytes = private_key.sign(message)

        return SignatureResult(
            signature_hex=signature_bytes.hex(),
            key_id=key_pair.key_id,
        )

    def sign_dict(self, data: dict, key_pair: KeyPair) -> SignatureResult:
        """
        Sign a dict via canonical JSON serialization.
        This is the primary signing method for block headers and proofs.
        """
        from crypto.canonical_json import canonical_encode
        message = canonical_encode(data)
        return self.sign(message, key_pair)

    def verify(
        self,
        message: Union[bytes, str],
        signature_hex: str,
        public_key_hex: str,
    ) -> bool:
        """
        Verify an Ed25519 signature.
        Returns True if valid, False if invalid or if crypto unavailable.
        """
        if not CRYPTO_AVAILABLE:
            logger.warning("Signature verification skipped — cryptography library not installed")
            return False

        if isinstance(message, str):
            message = message.encode("utf-8")

        try:
            public_key_bytes = bytes.fromhex(public_key_hex)
            # Load raw public key
            from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PublicKey
            public_key = Ed25519PublicKey.from_public_bytes(public_key_bytes)
            signature_bytes = bytes.fromhex(signature_hex)
            public_key.verify(signature_bytes, message)
            return True
        except InvalidSignature:
            return False
        except Exception as exc:
            logger.error("Signature verification error: %s", exc)
            return False

    def verify_dict(
        self,
        data: dict,
        signature_hex: str,
        public_key_hex: str,
    ) -> bool:
        """Verify a signature over a canonical JSON dict."""
        from crypto.canonical_json import canonical_encode
        message = canonical_encode(data)
        return self.verify(message, signature_hex, public_key_hex)

    def _require_crypto(self):
        if not CRYPTO_AVAILABLE:
            raise RuntimeError(
                "cryptography library required. Install with: pip install cryptography"
            )