"""
api/server.py

VFEL FastAPI Server — Phase 8.

Application factory pattern: create_app() wires all dependencies and
registers all routers. Run with:

    uvicorn api.server:app --host 0.0.0.0 --port 8000 --reload

Or programmatically:
    from api.server import create_app, VFELContext
    ctx = VFELContext(event_store=..., forest_manager=..., ...)
    app = create_app(ctx)

Dependencies:
    pip install fastapi uvicorn

All routes return JSON. Error responses follow RFC 7807 (Problem Details):
    {
        "type":   "https://vfel.io/errors/event-not-found",
        "title":  "Event Not Found",
        "status": 404,
        "detail": "No event with id=abc123",
    }

Health check:
    GET /health         → {"status": "ok", "version": "0.1.0"}
    GET /health/ready   → checks all subsystems are initialized

OpenAPI docs (auto-generated by FastAPI):
    http://localhost:8000/docs       (Swagger UI)
    http://localhost:8000/redoc      (ReDoc)
    http://localhost:8000/openapi.json
"""

from __future__ import annotations

import logging
import time
from dataclasses import dataclass, field
from typing import Optional

logger = logging.getLogger(__name__)


# ──────────────────────────────────────────────
# Dependency container — holds all live VFEL objects
# ──────────────────────────────────────────────

@dataclass
class VFELContext:
    """
    Single dependency container passed to all route handlers.
    Created once at startup, injected via FastAPI dependency.

    All fields are Optional so the server can start in degraded mode
    (e.g. read-only mode without an anchor manager).
    """
    event_store:         Optional[object] = None
    forest_manager:      Optional[object] = None
    block_store:         Optional[object] = None
    dag_builder:         Optional[object] = None
    anchor_manager:      Optional[object] = None
    key_registry:        Optional[object] = None

    # Proof generators — instantiated lazily on first request
    _inclusion_gen:      Optional[object] = field(default=None, repr=False)
    _ordering_gen:       Optional[object] = field(default=None, repr=False)
    _latency_gen:        Optional[object] = field(default=None, repr=False)
    _consistency_gen:    Optional[object] = field(default=None, repr=False)

    started_at: float = field(default_factory=time.time)

    def inclusion_proof_generator(self):
        if self._inclusion_gen is None and self.event_store:
            from proof_system.inclusion_proof import InclusionProofGenerator
            self._inclusion_gen = InclusionProofGenerator(
                self.event_store, self.forest_manager, self.block_store
            )
        return self._inclusion_gen

    def ordering_proof_generator(self):
        if self._ordering_gen is None and self.event_store:
            from proof_system.proofs import OrderingProofGenerator
            self._ordering_gen = OrderingProofGenerator(
                self.event_store, self.block_store, self.dag_builder
            )
        return self._ordering_gen

    def latency_proof_generator(self):
        if self._latency_gen is None and self.event_store:
            from proof_system.proofs import LatencyProofGenerator
            self._latency_gen = LatencyProofGenerator(
                self.event_store, self.block_store
            )
        return self._latency_gen

    def is_ready(self) -> dict[str, bool]:
        return {
            "event_store":    self.event_store is not None,
            "forest_manager": self.forest_manager is not None,
            "block_store":    self.block_store is not None,
            "dag_builder":    self.dag_builder is not None,
            "anchor_manager": self.anchor_manager is not None,
        }

    def uptime_seconds(self) -> float:
        return time.time() - self.started_at


# ──────────────────────────────────────────────
# Application factory
# ──────────────────────────────────────────────

def create_app(ctx: VFELContext):
    """
    Create and configure the FastAPI application.

    Registers all routers and middleware.
    Returns the ASGI app object.
    """
    try:
        from fastapi import FastAPI
        from fastapi.middleware.cors import CORSMiddleware
        import api.routes_events       as events_router
        import api.routes_proofs       as proofs_router
        import api.routes_verification as verify_router
    except ImportError as e:
        raise RuntimeError(
            f"FastAPI not installed. Run: pip install fastapi uvicorn\n{e}"
        )

    app = FastAPI(
        title="VFEL — Verifiable Financial Event Ledger",
        description=(
            "REST API for querying events, generating cryptographic proofs, "
            "and verifying ledger integrity."
        ),
        version="0.1.0",
        docs_url="/docs",
        redoc_url="/redoc",
    )

    # CORS — restrict in production
    app.add_middleware(
        CORSMiddleware,
        allow_origins=["*"],
        allow_methods=["GET", "POST"],
        allow_headers=["*"],
    )

    # Request timing middleware
    @app.middleware("http")
    async def add_process_time_header(request, call_next):
        start = time.perf_counter()
        response = await call_next(request)
        ms = (time.perf_counter() - start) * 1000
        response.headers["X-Process-Time-Ms"] = f"{ms:.2f}"
        return response

    # ── Health endpoints ───────────────────────────────────────────────

    @app.get("/health", tags=["health"])
    async def health():
        return {"status": "ok", "version": "0.1.0"}

    @app.get("/health/ready", tags=["health"])
    async def health_ready():
        readiness = ctx.is_ready()
        all_ready = all(readiness.values())
        return {
            "ready":          all_ready,
            "subsystems":     readiness,
            "uptime_seconds": round(ctx.uptime_seconds(), 1),
        }

    @app.get("/health/stats", tags=["health"])
    async def health_stats():
        stats = {"uptime_seconds": round(ctx.uptime_seconds(), 1)}
        if ctx.event_store:
            stats["total_events"] = ctx.event_store.total_events()
            stats["known_shards"] = len(ctx.event_store.known_shards())
        if ctx.block_store:
            stats.update(ctx.block_store.describe())
        if ctx.forest_manager:
            stats["forest_root"] = ctx.forest_manager.forest_root()
        if ctx.anchor_manager:
            stats["anchoring"] = ctx.anchor_manager.describe()
        return stats

    # ── Register route modules ────────────────────────────────────────

    app.include_router(
        events_router.build_router(ctx),
        prefix="/events",
        tags=["events"],
    )
    app.include_router(
        proofs_router.build_router(ctx),
        prefix="/proofs",
        tags=["proofs"],
    )
    app.include_router(
        verify_router.build_router(ctx),
        prefix="/verify",
        tags=["verification"],
    )

    # ── Ledger state endpoints ────────────────────────────────────────

    @app.get("/ledger/state", tags=["ledger"])
    async def ledger_state():
        state: dict = {}
        if ctx.event_store:
            state["total_events"]  = ctx.event_store.total_events()
            state["known_shards"]  = sorted(ctx.event_store.known_shards())
        if ctx.forest_manager:
            state["forest_root"]   = ctx.forest_manager.forest_root()
        if ctx.dag_builder:
            state["dag"] = ctx.dag_builder.describe()
        return state

    @app.get("/ledger/forest-root", tags=["ledger"])
    async def forest_root():
        if not ctx.forest_manager:
            from fastapi import HTTPException
            raise HTTPException(503, "ForestManager not initialized")
        root = ctx.forest_manager.forest_root()
        anchors = []
        if ctx.anchor_manager:
            records = ctx.anchor_manager.get_confirmed_for_root(root)
            anchors = [r.to_dict() for r in records]
        return {
            "forest_root": root,
            "confirmed_anchors": anchors,
        }

    @app.get("/ledger/blocks", tags=["ledger"])
    async def list_blocks(limit: int = 20, offset: int = 0):
        if not ctx.block_store:
            from fastapi import HTTPException
            raise HTTPException(503, "BlockStore not initialized")
        ordered = ctx.dag_builder.get_total_order() if ctx.dag_builder else []
        page = ordered[offset: offset + limit]
        blocks = []
        for bh in page:
            blk = ctx.block_store.get(bh)
            if blk:
                blocks.append({
                    "block_hash":   bh,
                    "height":       blk.height,
                    "event_count":  blk.header.event_range.event_count,
                    "forest_root":  blk.header.forest_root,
                    "parent_count": len(blk.header.parent_hashes),
                    "status":       blk.header.status.value,
                    "sealed_at_ns": blk.header.sealed_at_ns,
                })
        return {
            "total":  len(ordered),
            "offset": offset,
            "limit":  limit,
            "blocks": blocks,
        }

    @app.get("/ledger/blocks/{block_hash}", tags=["ledger"])
    async def get_block(block_hash: str):
        if not ctx.block_store:
            from fastapi import HTTPException
            raise HTTPException(503, "BlockStore not initialized")
        blk = ctx.block_store.get(block_hash)
        if not blk:
            from fastapi import HTTPException
            raise HTTPException(404, f"Block not found: {block_hash}")
        return blk.to_dict()

    logger.info("VFEL API application created with %d routes", len(app.routes))
    return app


# ──────────────────────────────────────────────
# Standalone entry point (for uvicorn)
# ──────────────────────────────────────────────

def _build_demo_context() -> VFELContext:
    """
    Build a fully-loaded VFELContext from test data.
    Used when running `python api/server.py` directly.
    """
    import sys, os
    sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

    from data_ingestion.pipeline import IngestionPipeline
    from ledger_core.event_store import EventStore
    from ledger_core.sequence_manager import SequenceManager
    from merkle_forest.forest_manager import ForestManager
    from merkle_forest.tree_snapshot import SnapshotStore
    from block_dag.block_store import BlockStore
    from block_dag.dag_builder import DAGBuilder
    from anchoring.anchor_manager import AnchorManager
    from anchoring.timestamp_anchor import LocalTimestampAnchor
    from anchoring.bitcoin_anchor import BitcoinAnchor
    from anchoring.ethereum_anchor import EthereumAnchor

    data_path = "data/vcp_rta_events.jsonl"
    if not os.path.exists(data_path):
        from data.generate_test_data import generate_chain
        generate_chain(n=500, output_path=data_path)

    seq_mgr   = SequenceManager()
    store     = EventStore(sequence_manager=seq_mgr)
    forest    = ForestManager(snapshot_store=SnapshotStore())
    blk_store = BlockStore()
    builder   = DAGBuilder(store, forest, blk_store, events_per_block=100)
    builder.initialize_genesis()

    pipeline = IngestionPipeline(file_paths=data_path, num_shards=8)
    for se in pipeline.run():
        ar = store.append(se.event)
        if ar.success:
            forest.append(ar.stored_event.shard_key, ar.stored_event.stored_event_hash)
            builder.feed(ar.stored_event)
    builder.flush()

    anchor_mgr = AnchorManager()
    anchor_mgr.register_backend(LocalTimestampAnchor(node_id="demo-node"))
    anchor_mgr.register_backend(BitcoinAnchor(mode="simulation"))
    anchor_mgr.register_backend(EthereumAnchor(mode="simulation"))
    anchor_mgr.anchor(forest.forest_root(), metadata={"source": "startup"})

    logger.info(
        "Demo context loaded: %d events, %d blocks",
        store.total_events(),
        len(blk_store.all_blocks()),
    )
    return VFELContext(
        event_store=store,
        forest_manager=forest,
        block_store=blk_store,
        dag_builder=builder,
        anchor_manager=anchor_mgr,
    )


# Importable ASGI app — `uvicorn api.server:app`
try:
    _ctx = _build_demo_context()
    app = create_app(_ctx)
except Exception as _e:
    logger.warning("Could not build demo context: %s", _e)
    app = None